modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="ancient_flame_balrog"
version="1.0.0"
displayName="Ancient Flame Balrog"
description='''Adds a full Ancient Flame Balrog boss mob.'''
